import { Champion, ChampionBase, Region, Role, GrowthCurve, DamageType } from "./types";
import { levelUpChampion } from "./leveling";

export const DEMACIA_CHAMPIONS: ChampionBase[] = [
    {
        id: 1,
        name: "Fiora",
        region: Region.Demacia,
        role: Role.Fighter,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Late,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Early,
        level: 1,
        maxHp: 105,
        ap: 0,
        attack: 19,
        armor: 10,
        magic_resist: 8,
        speed: 13,
        damageType: DamageType.Physical
        
    },
    {
        id: 2,
        name: "Galio",
        region: Region.Demacia,
        role: Role.Tank,
        apGrowth: GrowthCurve.Flat,
        attackGrowth: GrowthCurve.Flat,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 115,
        ap: 12,
        attack: 7,
        armor: 18,
        magic_resist: 15,
        speed: 5,
        damageType: DamageType.Magical
    },
    {
        id: 3,
        name: "Garen",
        region: Region.Demacia,
        role: Role.Fighter,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Mid,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Early,
        speedGrowth: GrowthCurve.Early,
        level: 1,
        maxHp: 110,
        ap: 0,
        attack: 19,
        armor: 12,
        magic_resist: 9,
        speed: 7,
        damageType: DamageType.Physical

    },
    {
        id: 4,
        name: "Jarvan IV",
        region: Region.Demacia,
        role: Role.Fighter,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Early,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 120,
        ap: 0,
        attack: 20,
        armor: 15,
        magic_resist: 12,
        speed: 10,
        damageType: DamageType.Physical
    },
    {
        id: 5,
        name: "Kayle",
        region: Region.Demacia,
        role: Role.Marksman,
        apGrowth: GrowthCurve.Late,
        attackGrowth: GrowthCurve.Mid,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Late,
        level: 1,
        maxHp: 90,
        ap: 12,
        attack: 14,
        armor: 8,
        magic_resist: 7,
        speed: 11,
        damageType: DamageType.Mixed
    },
    {
        id: 6,
        name: "Lux",
        region: Region.Demacia,
        role: Role.Mage,
        apGrowth: GrowthCurve.Early,
        attackGrowth: GrowthCurve.None,
        hpGrowth: GrowthCurve.Early,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 90,
        ap: 15,
        attack: 5,
        armor: 6,
        magic_resist: 5,
        speed: 10,
        damageType: DamageType.Magical
    },
    {
        id: 7,
        name: "Lucian",
        region: Region.Demacia,
        role: Role.Marksman,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Early,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Mid,
        level: 1,
        maxHp: 90,
        ap: 0,
        attack: 21,
        armor: 7,
        magic_resist: 5,
        speed: 12,
        damageType: DamageType.Physical
    },
    {
        id: 8,
        name: "Morgana",
        region: Region.Demacia,
        role: Role.Mage,
        apGrowth: GrowthCurve.Early,
        attackGrowth: GrowthCurve.None,
        hpGrowth: GrowthCurve.Early,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 95,
        ap: 18,
        attack: 3,
        armor: 7,
        magic_resist: 6,
        speed: 9,
        damageType: DamageType.Magical
    },
    {
        id: 9,
        name: "Poppy",
        region: Region.Demacia,
        role: Role.Tank,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Flat,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 135,
        attack: 15,
        ap: 0,
        armor: 17,
        magic_resist: 15,
        speed: 6,
        damageType: DamageType.Physical
    },
    {
        id: 10,
        name: "Quinn",
        region: Region.Demacia,
        role: Role.Marksman,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Mid,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Early,
        level: 1,
        maxHp: 95,
        ap: 0,
        attack: 19,
        armor: 6,
        magic_resist: 5,
        speed: 15,
        damageType: DamageType.Physical
    },
    {
        id: 11,
        name: "Shyvana",
        region: Region.Demacia,
        role: Role.Fighter,
        apGrowth: GrowthCurve.Mid,
        attackGrowth: GrowthCurve.Mid,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 125,
        ap: 10,
        attack: 20,
        armor: 10,
        magic_resist: 8,
        speed: 8,
        damageType: DamageType.Mixed
    },
    {
        id: 12,
        name: "Sona",
        region: Region.Demacia,
        role: Role.Support,
        apGrowth: GrowthCurve.Mid,
        attackGrowth: GrowthCurve.None,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 85,
        ap: 12,
        attack: 5,
        armor: 6,
        magic_resist: 5,
        speed: 10,
        damageType: DamageType.Magical
    },
    {
        id: 13,
        name: "Sylas",
        region: Region.Demacia,
        role: Role.Mage,
        apGrowth: GrowthCurve.Mid,
        attackGrowth: GrowthCurve.None,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 105,
        ap: 17,
        attack: 12,
        armor: 11,
        magic_resist: 9,
        speed: 9,
        damageType: DamageType.Magical
    },
    {
        id: 14,
        name: "Vayne",
        region: Region.Demacia,
        role: Role.Marksman,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Late,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Mid,
        level: 1,
        maxHp: 90,
        ap: 0,
        attack: 23,
        armor: 6,
        magic_resist: 5,
        speed: 14,
        damageType: DamageType.Physical
    },
    {
        id: 15,
        name: "Xin Zhao",
        region: Region.Demacia,
        role: Role.Fighter,
        apGrowth: GrowthCurve.None,
        attackGrowth: GrowthCurve.Mid,
        hpGrowth: GrowthCurve.Mid,
        defenseGrowth: GrowthCurve.Mid,
        speedGrowth: GrowthCurve.Flat,
        level: 1,
        maxHp: 110,
        ap: 0,
        attack: 21,
        armor: 16,
        magic_resist: 14,
        speed: 11,
        damageType: DamageType.Physical
    },
    {
        id: 16,
        name: "Locke",
        region: Region.Demacia,
        role: Role.Assassin,
        apGrowth: GrowthCurve.Early,
        attackGrowth: GrowthCurve.None,
        hpGrowth: GrowthCurve.Flat,
        defenseGrowth: GrowthCurve.Flat,
        speedGrowth: GrowthCurve.Early,
        level: 1,
        maxHp: 90,
        ap: 20,
        attack: 9,
        armor: 7,
        magic_resist: 5,
        speed: 10,
        damageType: DamageType.Magical
    }
];

export function createChampionInstance(champion: ChampionBase): Champion {
    const targetLevel = champion.level;
    const instance: Champion = {
        ...champion,
        level: 1,
        currentHp: champion.maxHp
    };

    for (let level = 1; level < targetLevel; level += 1) {
        levelUpChampion(instance);
    }

    instance.currentHp = instance.maxHp;
    return instance;
}
